spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_charge?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 20050210
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.gdpu.hospitalcharge.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080